%YAML 1.1
---
# This is a minimal configuration for Suricata in Docker.
# It tells Suricata to monitor the primary network interface (eth0).
# For more advanced configurations, see the official Suricata documentation.

# Step 1: configure AF_PACKET
af-packet:
  - interface: eth0
    # The default cluster-id is 0, so all threads will load balance packets.
    # Set cluster-type to 'cluster_flow' for AF_PACKET load balancing.
    cluster-type: cluster_flow
    cluster-id: 99
    # AF_PACKET will not be in promiscuous mode so we only get traffic to and from the interface.
    # To run in promiscuous mode, uncomment the following line.
    # promiscuous: yes

# Step 2: configure outputs
# A line based alerts log with a human-readable format.
outputs:
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - files
        - smtp
        - flow
        - netflow

# Step 3: configure community-id
# This adds a field to EVE records that is the same across protocols for the same flow.
# Useful for correlating events in your SIEM.
community-id: true

# Step 4: configure variables
vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
    HTTP_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"
    AIM_SERVERS: "$EXTERNAL_NET"
    DC_SERVERS: "$HOME_NET"
    DNP3_SERVER: "$HOME_NET"
    DNP3_CLIENT: "$HOME_NET"
    MODBUS_CLIENT: "$HOME_NET"
    MODBUS_SERVER: "$HOME_NET"
    ENIP_CLIENT: "$HOME_NET"
    ENIP_SERVER: "$HOME_NET"
  port-groups:
    HTTP_PORTS: "80"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: 1521
    SSH_PORTS: 22
    DNP3_PORTS: 20000
    MODBUS_PORTS: 502
    FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
    FTP_PORTS: 21
    GENEVE_PORTS: 6081
    VXLAN_PORTS: 4789
    TEREDO_PORTS: 3544

# Step 5: configure default rule paths
default-rule-path: /var/lib/suricata/rules
rule-files:
  - suricata.rules

